name = "ucloud-bot"
main = "src/worker.ts"
compatibility_date = "2023-10-31"


[[d1_databases]]
binding = "DB"
database_name = "ucloud-bot"
database_id = "xxx"

[vars]
ENV_BOT_TOKEN = "xxx"
ENV_BOT_SECRET = 'xxx'
API_ENDPOINT = "xxx"

[triggers]
# every 30 minutes
crons = ["*/30 * * * *"]