name = "ucloud-bot"
main = "src/worker.ts"
compatibility_date = "2023-10-31"


[[d1_databases]]
binding = "DB"
database_name = "ucloud-bot"
database_id = "2dc2a7e6-ece2-4a4b-9e01-5928f8d4bb4d"

[vars]
API_SCHEDULE = "https://ucloud.youxam.one"
API_FETCH = ["https://ucloud.youxam.one"]


[triggers]
# every 30 minutes
crons = ["*/30 * * * *"]